### PR TITLE
cleaning of pr #15692 and test case for issue #6913

### PR DESCRIPTION
**Pull request by RituRajSingh878**
#### Brief description of what is fixed or changed
Fixes #15665  #15528 and added test case for #6913

### CODE REVIEW

**Comment by asmeurer** [comment]
This doesn't do anything about https://github.com/sympy/sympy/issues/15528, though (`Mul(Matrix([[3]]), x).subs(x, 2.0)`). I think a fix for this needs to be more carefully thought about.

**Comment by RituRajSingh878** [comment]
@asmeurer can you please check it so i can do further work.

**Comment by asmeurer** [comment]
This will take me some time to examine, to see if it really addresses the issue fully. In the meantime, you can add a test for [sympy#15528](https://github.com/sympy/sympy/issues/15528).

**Comment by asmeurer** [comment]
I have gone with what I believe is a more robust fix at https://github.com/sympy/sympy/pull/15948. If you want you can help review it. 

As for sympy#6913, I believe it already works in master, so I would suggest making a separate pull request to SymPy adding the test case so the issue can be closed.

**Pull request closed without merging**
