### PR TITLE
Update this branch with master, fix merge conflicts and replace deprecated is_bounded with is_finite

### PR DESCRIPTION
**Pull request by debugger22**

### CODE REVIEW

**Comment by debugger22** [comment]
Just last two commits are not in sympy master.

**Comment by asmeurer** [comment]
GitHub makes this a pain to look at but according to https://github.com/sympy/sympy/compare/master...debugger22:aaron-assumptions?expand=1 I think you are correct.

**Comment by asmeurer** [comment]
There are test failures. They look like they might be related to the code you changed.

**Comment by debugger22** [comment]
There was one is_bounded still left. Fixed it.

**Comment by debugger22** [comment]
Tests passed.

**Pull request merged**
